# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'APE.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(983, 653)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 10, 871, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.atab = QtWidgets.QWidget()
        self.atab.setObjectName("atab")
        self.blankapp = QtWidgets.QPushButton(self.atab)
        self.blankapp.setGeometry(QtCore.QRect(220, 20, 113, 32))
        self.blankapp.setObjectName("blankapp")
        self.tempapp = QtWidgets.QPushButton(self.atab)
        self.tempapp.setGeometry(QtCore.QRect(60, 20, 113, 32))
        self.tempapp.setObjectName("tempapp")
        self.treeWidget = QtWidgets.QTreeWidget(self.atab)
        self.treeWidget.setGeometry(QtCore.QRect(40, 60, 321, 431))
        self.treeWidget.setObjectName("treeWidget")
        self.findbox = QtWidgets.QLineEdit(self.atab)
        self.findbox.setGeometry(QtCore.QRect(460, 40, 161, 21))
        self.findbox.setObjectName("findbox")
        self.replacebox = QtWidgets.QLineEdit(self.atab)
        self.replacebox.setGeometry(QtCore.QRect(650, 40, 161, 21))
        self.replacebox.setObjectName("replacebox")
        self.label = QtWidgets.QLabel(self.atab)
        self.label.setGeometry(QtCore.QRect(460, 20, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.atab)
        self.label_2.setGeometry(QtCore.QRect(650, 20, 60, 16))
        self.label_2.setObjectName("label_2")
        self.fandrbutton = QtWidgets.QPushButton(self.atab)
        self.fandrbutton.setGeometry(QtCore.QRect(540, 70, 181, 32))
        self.fandrbutton.setObjectName("fandrbutton")
        self.addbtn = QtWidgets.QPushButton(self.atab)
        self.addbtn.setGeometry(QtCore.QRect(510, 110, 113, 32))
        self.addbtn.setObjectName("addbtn")
        self.removebtn = QtWidgets.QPushButton(self.atab)
        self.removebtn.setGeometry(QtCore.QRect(640, 110, 113, 32))
        self.removebtn.setObjectName("removebtn")
        self.copybtn = QtWidgets.QPushButton(self.atab)
        self.copybtn.setGeometry(QtCore.QRect(520, 160, 231, 32))
        self.copybtn.setObjectName("copybtn")
        self.itable = QtWidgets.QTableWidget(self.atab)
        self.itable.setGeometry(QtCore.QRect(470, 310, 331, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itable.sizePolicy().hasHeightForWidth())
        self.itable.setSizePolicy(sizePolicy)
        self.itable.setObjectName("itable")
        self.itable.setColumnCount(2)
        self.itable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.itable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.itable.setHorizontalHeaderItem(1, item)
        self.saveasbtn = QtWidgets.QPushButton(self.atab)
        self.saveasbtn.setGeometry(QtCore.QRect(680, 230, 113, 32))
        self.saveasbtn.setObjectName("saveasbtn")
        self.fnamebox = QtWidgets.QLineEdit(self.atab)
        self.fnamebox.setGeometry(QtCore.QRect(460, 230, 191, 21))
        self.fnamebox.setText("")
        self.fnamebox.setObjectName("fnamebox")
        self.connectbtn = QtWidgets.QPushButton(self.atab)
        self.connectbtn.setGeometry(QtCore.QRect(530, 270, 221, 32))
        self.connectbtn.setObjectName("connectbtn")
        self.disconnectbtn = QtWidgets.QPushButton(self.atab)
        self.disconnectbtn.setGeometry(QtCore.QRect(530, 510, 221, 32))
        self.disconnectbtn.setObjectName("disconnectbtn")
        self.simBox = QtWidgets.QCheckBox(self.atab)
        self.simBox.setGeometry(QtCore.QRect(390, 110, 111, 31))
        self.simBox.setObjectName("simBox")
        self.simBox.setChecked(True)
        self.tabWidget.addTab(self.atab, "")
        self.ptab = QtWidgets.QWidget()
        self.ptab.setObjectName("ptab")
        self.pbox = QtWidgets.QListWidget(self.ptab)
        self.pbox.setGeometry(QtCore.QRect(20, 20, 256, 221))
        self.pbox.setAcceptDrops(False)
        self.pbox.setLineWidth(1)
        self.pbox.setModelColumn(0)
        self.pbox.setObjectName("pbox")
        self.rbox = QtWidgets.QTableWidget(self.ptab)
        self.rbox.setGeometry(QtCore.QRect(500, 40, 341, 171))
        self.rbox.setDragEnabled(True)
        self.rbox.setObjectName("rbox")
        self.rbox.setColumnCount(2)
        self.rbox.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rbox.setHorizontalHeaderItem(1, item)
        self.pbox_2 = QtWidgets.QListWidget(self.ptab)
        self.pbox_2.setGeometry(QtCore.QRect(20, 270, 256, 231))
        self.pbox_2.setAcceptDrops(False)
        self.pbox_2.setLineWidth(1)
        self.pbox_2.setModelColumn(0)
        self.pbox_2.setObjectName("pbox_2")
        self.rbox_2 = QtWidgets.QTableWidget(self.ptab)
        self.rbox_2.setGeometry(QtCore.QRect(500, 290, 331, 171))
        self.rbox_2.setDragEnabled(True)
        self.rbox_2.setObjectName("rbox_2")
        self.rbox_2.setColumnCount(2)
        self.rbox_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rbox_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rbox_2.setHorizontalHeaderItem(1, item)
        self.upbtn = QtWidgets.QPushButton(self.ptab)
        self.upbtn.setGeometry(QtCore.QRect(330, 380, 113, 32))
        self.upbtn.setObjectName("upbtn")
        self.downbtn = QtWidgets.QPushButton(self.ptab)
        self.downbtn.setGeometry(QtCore.QRect(330, 430, 113, 32))
        self.downbtn.setObjectName("downbtn")
        self.createbtn = QtWidgets.QPushButton(self.ptab)
        self.createbtn.setGeometry(QtCore.QRect(330, 60, 113, 32))
        self.createbtn.setObjectName("createbtn")
        self.rbtn = QtWidgets.QPushButton(self.ptab)
        self.rbtn.setGeometry(QtCore.QRect(330, 330, 113, 32))
        self.rbtn.setObjectName("rbtn")
        self.abtn = QtWidgets.QPushButton(self.ptab)
        self.abtn.setGeometry(QtCore.QRect(330, 280, 113, 32))
        self.abtn.setObjectName("abtn")
        self.runCurrentbtn = QtWidgets.QPushButton(self.ptab)
        self.runCurrentbtn.setGeometry(QtCore.QRect(150, 500, 113, 32))
        self.runCurrentbtn.setObjectName("runCurrentbtn")
        self.RunListbtn = QtWidgets.QPushButton(self.ptab)
        self.RunListbtn.setGeometry(QtCore.QRect(30, 500, 111, 32))
        self.RunListbtn.setObjectName("RunListbtn")
        self.showeproc = QtWidgets.QPushButton(self.ptab)
        self.showeproc.setGeometry(QtCore.QRect(330, 100, 113, 32))
        self.showeproc.setObjectName("showeproc")
        self.tabWidget.addTab(self.ptab, "")
        self.utab = QtWidgets.QWidget()
        self.utab.setObjectName("utab")
        self.tabWidget.addTab(self.utab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pbox.setCurrentRow(-1)
        self.pbox_2.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.blankapp.setText(_translate("MainWindow", "Refresh"))
        self.tempapp.setText(_translate("MainWindow", "Template"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Apparatus"))
        self.label.setText(_translate("MainWindow", "Find"))
        self.label_2.setText(_translate("MainWindow", "Replace"))
        self.fandrbutton.setText(_translate("MainWindow", "Find and Replace"))
        self.addbtn.setText(_translate("MainWindow", "Add"))
        self.removebtn.setText(_translate("MainWindow", "Remove"))
        self.copybtn.setText(_translate("MainWindow", "Copy to Procedure Requirement"))
        item = self.itable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Key"))
        item = self.itable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.saveasbtn.setText(_translate("MainWindow", "Save As"))
        self.connectbtn.setText(_translate("MainWindow", "Connect All Devices"))
        self.disconnectbtn.setText(_translate("MainWindow", "Disconnect All Devices"))
        self.simBox.setText(_translate("MainWindow", "Simulation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.atab), _translate("MainWindow", "Apparatus"))
        item = self.rbox.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Requirement"))
        item = self.rbox.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item"))
        item = self.rbox_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Requirement"))
        item = self.rbox_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Item"))
        self.upbtn.setText(_translate("MainWindow", "Up"))
        self.downbtn.setText(_translate("MainWindow", "Down"))
        self.createbtn.setText(_translate("MainWindow", "Create"))
        self.rbtn.setText(_translate("MainWindow", "Remove"))
        self.abtn.setText(_translate("MainWindow", "Add"))
        self.runCurrentbtn.setText(_translate("MainWindow", "Run Current"))
        self.RunListbtn.setText(_translate("MainWindow", "Run List"))
        self.showeproc.setText(_translate("MainWindow", "Display Eprocs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ptab), _translate("MainWindow", "Procedure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.utab), _translate("MainWindow", "Utilities"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

